# Generated by Django 4.1.4 on 2023-02-17 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bon_Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('I', 'Entrée'), ('E', 'Sortie')], max_length=1)),
                ('quantite', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomClient', models.CharField(max_length=100)),
                ('AdrClient', models.CharField(max_length=200)),
                ('TelClient', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomFour', models.CharField(max_length=100)),
                ('AdrFour', models.CharField(max_length=200)),
                ('TelFour', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('B', 'Brut'), ('F', 'Fin')], max_length=1)),
                ('quantite', models.IntegerField()),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Bon_Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('I', 'Entrée'), ('E', 'Sortie')], max_length=1)),
                ('quantite', models.IntegerField()),
                ('date', models.DateField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.bon_commande')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.fournisseur')),
            ],
        ),
        migrations.AddField(
            model_name='bon_commande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.client'),
        ),
        migrations.AddField(
            model_name='bon_commande',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.produit'),
        ),
    ]
